#!/bin/sh

RESTORE='\033[0m'
RED='\033[00;31m'
GREEN='\033[00;32m'
YELLOW='\033[00;33m'
BLUE='\033[00;34m'
MAGENTA='\033[00;35m'
CYAN='\033[00;36m'
WHITE='\033[00;37m'

FILE_FOUND=''

check_for()
{
  if [[ $(git diff --cached -- :/$file | grep -nE "^\+\s*$1{4,}") ]]; then
    ROW_NUMBERS=$(grep -nE "^\s*$1{4,}" $file | sed -e 's/\([[:digit:]]\+\):.\+/\1/')
    if [[ $? == 0 ]]; then
      for ROW in $ROW_NUMBERS; do
        FILE_FOUND+="${RED}$file${RESTORE}:${GREEN}$ROW ${RESTORE}contains ${CYAN}$1$1$1$1 ${RESTORE}message.\n"
      done
    fi
  fi
}

for file in $(git diff --cached --name-only); do
  check_for "<"
  check_for "="
  check_for ">"
done

if [[ ! -z $FILE_FOUND ]]; then
  echo -e "${YELLOW}###################"
  echo "# COMMIT REJECTED #"
  echo "###################"
  echo -e "$FILE_FOUND#"
  echo    "# You are trying to commit a merge conflict."
  echo "#"
  exit 1
fi

exit 0
